create table if not exists public.profiles (
  id uuid not null,
  updated_at timestamptz default timezone('utc', now()),
  full_name text,
  role text default 'staff'
);

create table if not exists public.stores (
  id uuid default gen_random_uuid(),
  created_at timestamptz not null default timezone('utc', now()),
  store_name text not null,
  boss_id uuid
);

create table if not exists public.questions (
  id bigint generated by default as identity,
  created_at timestamptz not null default now(),
  store_id uuid,
  question text,
  question_type text,
  expected_category text,
  expected_answer text
);

alter table public.manuals
  add column if not exists store_id uuid;

create index if not exists manuals_store_id_idx
  on public.manuals (store_id);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'profiles_pkey'
      and conrelid = 'public.profiles'::regclass
  ) then
    alter table public.profiles
      add constraint profiles_pkey primary key (id);
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'profiles_id_fkey'
      and conrelid = 'public.profiles'::regclass
  ) then
    alter table public.profiles
      add constraint profiles_id_fkey
      foreign key (id) references auth.users(id) on delete cascade;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'profiles_role_check'
      and conrelid = 'public.profiles'::regclass
  ) then
    alter table public.profiles
      add constraint profiles_role_check
      check (role in ('boss', 'staff'));
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'stores_pkey'
      and conrelid = 'public.stores'::regclass
  ) then
    alter table public.stores
      add constraint stores_pkey primary key (id);
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'stores_boss_id_fkey'
      and conrelid = 'public.stores'::regclass
  ) then
    alter table public.stores
      add constraint stores_boss_id_fkey
      foreign key (boss_id) references public.profiles(id) on delete cascade;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'manuals_store_id_fkey'
      and conrelid = 'public.manuals'::regclass
  ) then
    alter table public.manuals
      add constraint manuals_store_id_fkey
      foreign key (store_id) references public.stores(id) on delete cascade;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'questions_pkey'
      and conrelid = 'public.questions'::regclass
  ) then
    alter table public.questions
      add constraint questions_pkey primary key (id);
  end if;
end
$$;

alter table public.profiles enable row level security;
alter table public.stores enable row level security;
alter table public.questions enable row level security;